name: TopSlimOffice SG
favicon: null
layout_spectrum: 0.7182414280250669
typography_spectrum: 0.9294703274499625
author:
  name: Brendan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  brandStrength: 0.33648132998496294
  lightness: 0.8379048046190292
  saturation: 0.2605399733874947
  rhythmicContrast: 0.5605330623220652
purpose: []
