purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.3364813299849629
  lightness: 0.8476703
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  rhythmicContrast: 0.9856631
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: TopSlimOffice SG
author:
  name: Brendan
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.761830752948299
layout_spectrum: 0.6520337858237326
